POL-278: add BillActionBadge to MinutesCard
politylink/politylink-gatsby pull request #70
Opened 2021-04-27 14:17 UTC by masastat

2021-04-27 15:42 UTC, masastat commented on src/utils/sortutils.js
> +    return parseInt(urls[0].url.split('/').slice(-1)[0])
BillAction.urls[0].url（speech url）からspeech orderを抽出して、それをbillActionのオーダーとして使っています。

2021-04-28 08:04 UTC, MitsukiUsui reviewed
スクショも貼ってもらえると助かります。

2021-04-28 08:04 UTC, MitsukiUsui commented on src/utils/formatutils.js
> +            return '委員長報告'
例えば今後typeを追加してどのケースにも当てはまらないとどうなる？

2021-04-28 08:04 UTC, MitsukiUsui commented on src/templates/bill.js
> +                    billActions(filter:{belongedToBill:{id:$billId}}) { type, urls { url } }
Bill.billActionsからアクセスしているのでfilterいらない？

2021-04-28 08:44 UTC, masastat commented on src/utils/sortutils.js
> +    return parseInt(urls[0].url.split('/').slice(-1)[0])
> あと最後の[0]は何のためだっけ？

split('/').slice(-1)の返り値は長さ1の配列なので、最後に[0]があります。

> BillActionにorderInMinutesを直接しちゃって良いかなと思います。

表示順を固定するということですか？

2021-04-28 08:45 UTC, masastat commented on src/utils/formatutils.js
> +            return '委員長報告'
breakとdefaultを追加します。

2021-04-28 08:56 UTC, masastat commented on src/templates/bill.js
> +                    billActions(filter:{belongedToBill:{id:$billId}}) { type, urls { url } }
このfilterは必要だと思います。
bill.beDiscussedByMinutes.billActions とBillからMinutesを経由してBillActionにアクセスしているので、billActionをbillIdでフィルターしないとそのminutesに紐づいたbillAction全てが返ってきます。

2021-04-28 09:51 UTC, MitsukiUsui commented on src/utils/sortutils.js
> +    return parseInt(urls[0].url.split('/').slice(-1)[0])
ごめんtypoがありました。GraphQLに直接BillAction.orderInMinutesを保存するということです。

2021-04-28 09:52 UTC, MitsukiUsui commented on src/templates/bill.js
> +                    billActions(filter:{belongedToBill:{id:$billId}}) { type, urls { url } }
ほんとだ、bill.billActionsじゃないのか、説明ありがとう。

2021-05-02 13:30 UTC, masastat commented
![Uploading Screen Shot 2021-05-02 at 22.27.19.png…]()

2021-05-02 13:31 UTC, masastat commented
![Screen Shot 2021-05-02 at 22 27 19](https://user-images.githubusercontent.com/20146973/116814927-23dc0d00-ab96-11eb-8670-2d4f817c0ff1.png)

2021-05-03 02:49 UTC, MitsukiUsui approved these changes
細かいコメントをつけましたがLGTMです。

2021-05-03 02:49 UTC, MitsukiUsui commented on src/utils/sortutils.js
> +    })
```
return sortIntAsc(billActions, billlAction =>billlAction.belongedToSpeech.orderInMinutes)
```
かな？

2021-05-03 02:49 UTC, MitsukiUsui commented on src/templates/bill.js
> +                    billActions(filter:{belongedToBill:{id:$billId}}) { type,  belongedToSpeech { orderInMinutes } }
fieldごとに改行してもらえると将来変更が追いやすくなって良いかなと思います（ndlUrlも取得するとか）。


```
billActions(filter:{belongedToBill:{id:$billId}}) {
    type
    belongedToSpeech {
       orderInMinutes 
   }
}
```

2021-05-03 02:49 UTC, MitsukiUsui commented on src/components/minutesCard.js
> +                        const BillActionType = translateBillActionType(billAction.type)
nit: 先頭は小文字で`billActionType`

2021-05-03 03:08 UTC, MitsukiUsui requested changes
タイムラインと委員会詳細ページを見ようとするとsortBillActionsでエラーが出ます。確認できますか？
```
TypeError: Cannot read property 'sort' of undefined
```

MinutesCard内でbillActionsのnullチェックをする必要がありそう。

2021-05-03 09:48 UTC, masastat commented
> タイムラインと委員会詳細ページを見ようとするとsortBillActionsでエラーが出ます。確認できますか？
> 
> ```
> TypeError: Cannot read property 'sort' of undefined
> ```
> 
> MinutesCard内でbillActionsのnullチェックをする必要がありそう。

確認できました。
timeline.jsでもMinutesCardを表示しているのでbillActionsがundefinedになるんですね。
MinutesCardにbillActionsのnullチェックを入れます。

2021-05-03 10:05 UTC, masastat commented on src/utils/sortutils.js
> +    })
`return sortIntAsc(billActions, billlAction =>billlAction.belongedToSpeech.orderInMinutes)`
に変えます。

2021-05-03 10:07 UTC, masastat commented on src/templates/bill.js
> +                    billActions(filter:{belongedToBill:{id:$billId}}) { type,  belongedToSpeech { orderInMinutes } }
改行します。

2021-05-03 10:08 UTC, masastat commented on src/components/minutesCard.js
> +                        const BillActionType = translateBillActionType(billAction.type)
billActionTypeにします。

2021-05-04 14:43 UTC, MitsukiUsui approved these changes
LGTM

2021-05-04 14:43 UTC, MitsukiUsui commented on src/components/minutesCard.js
> +        billActions = sortBillActions(props.billActions)
三項演算子を使うとシンプルに書けそう
```
const billActions = props.billActions ? sortBillActions(props.billActions) : []
```

2021-05-04 14:43 UTC, MitsukiUsui commented on src/components/minutesCard.js
> +                        }
ESLintErrorが出てたので修正しました。

```
warn ESLintError:
/Users/musui/politylink/politylink-gatsby/src/components/minutesCard.js
  18:25  warning  Nested block is redundant
```

2021-05-04 14:47 UTC, merged